from typing import Protocol


class UserManagerProtocol(Protocol):
    token: str
    token_vkme: str
    balance: int
    squad: str
    rank: int
    premium: bool
    username: str
    prefix_command: str
    prefix_script: str
    prefix_admin: str
    trust_prefix: str
    ignore_list: list
    trust_list: list

    async def init(self) -> None: ...
    async def set_username(self, username: str) -> None: ...
    async def set_rank(self, rank: int) -> None: ...
    async def set_balance(self, balance: int, action: str) -> None: ...
    async def set_ignore_list(self, user_id: int, action: str) -> None: ...
    async def set_trusted_list(self, user_id: int, action: str) -> None: ...
    async def set_prefix_commands(self, prefix: str) -> None: ...
    async def set_prefix_scripts(self, prefix: str) -> None: ...
    async def set_prefix_admin(self, prefix: str) -> None: ...
